version: '3'
services:
  web:
    container_name: dev_ltc_nginx
    image: nginx:latest
    ports:
      - "9342:9342"
    links:
      - litecoind
    volumes:
      - ./ng.conf:/etc/nginx/conf.d/ng.conf
  litecoind:
    build: .
    image: dev/ltc
    container_name: dev_ltc
    command: litecoind -conf=/data/litecoin.conf -addresstype=legacy
    expose:
     - "9332"
    volumes:
     - .:/data