version: '3'
services:
  btc_web:
    container_name: dev_btc_nginx
    image: nginx:latest
    ports:
      - "8342:8342"
    links:
      - bitcoind
    volumes:
      - ./ng.conf:/etc/nginx/conf.d/ng.conf
  bitcoind:
    build: .
    image: dev/btc
    container_name: dev_btc
    command: bitcoind -conf=/data/bitcoin.conf -addresstype=legacy
    expose:
     - "8332"
    volumes:
     - .:/data